Update style-guides.md
oceanprotocol/dev-ocean pull request #110
Opened 2019-01-07 07:57 UTC by aj07

https://github.com/oceanprotocol/keeper-contracts/issues/241

2019-01-07 08:03 UTC, H34D commented
@aj07 can you please update the ethlint rules to reflect those changes? https://solium.readthedocs.io/en/latest/user-guide.html#list-of-style-rules `max-len`

2019-01-07 11:21 UTC, aaitor approved these changes

2019-01-09 10:53 UTC, H34D requested changes
please update this as well: https://github.com/oceanprotocol/dev-ocean/blob/0cd380d9bfdfa39054cf2b2eb298e772b2c712cc/doc/development/style-guides.md#ethlint

2019-01-09 12:05 UTC, H34D approved these changes

2019-01-09 12:06 UTC, merged