#112: update the squid API spec.
oceanprotocol/dev-ocean pull request #114
Opened 2019-01-14 15:06 UTC by ssallam

2019-01-29 17:19 UTC, Pedro-vk approved these changes
LGTM :+1:

2019-01-30 08:04 UTC, aaitor requested changes
Nice advance @ssallam , please take a look at the comments but this start to have a good shape

2019-01-30 08:04 UTC, aaitor commented on doc/architecture/squid.md
> +        agreementId:
missing definition

2019-01-30 08:04 UTC, aaitor commented on doc/architecture/squid.md
> +               mode: ?
what is the mode parameter?

2019-01-30 08:04 UTC, aaitor commented on doc/architecture/squid.md
> +| request_tokens      |                                     |        |      |      |
missing return value

2019-01-30 08:04 UTC, aaitor commented on doc/architecture/squid.md
> +## ocean.secret_store
Are not private functions?
If are private I'm okay specifying here but detailing are private. 
I would add references to the existing Secret Store documentation in dev-ocea

2019-01-30 20:02 UTC, ssallam commented on doc/architecture/squid.md
> +| Ocean.getInstance() / Ocean()      | Ocean instance             |        |      |      |
The table is a compact list of all functions in a module, and shows the status of implementation in the different languages.

We can move this to a separate page if does not seem to fit here.

2019-01-30 20:03 UTC, ssallam commented on doc/architecture/squid.md
Will add it as suggested.

2019-01-30 20:23 UTC, ssallam commented on doc/architecture/squid.md
>  **Note 1: "Provider" was renamed to Aquarius and some of its functionality was moved over to Brizo. This page hasn't been updated to reflect that change yet.**
Deleted.

2019-01-30 20:23 UTC, ssallam commented on doc/architecture/squid.md
> +        agreementId:
Added the definition.

2019-01-30 20:24 UTC, ssallam commented on doc/architecture/squid.md
> +               mode: ?
Replaced it for now with `resultPath`

2019-01-31 16:22 UTC, aaitor approved these changes

2019-01-31 20:24 UTC, merged