Copy-edited computing-services.md
oceanprotocol/dev-ocean pull request #91
Opened 2018-11-23 11:45 UTC by ttmc

The `computing-services.md` file in the dev-ocean repo is publicly-readable in the new docs site at https://betadocs.oceanprotocol.com/concepts/computing-services/ so I copy-edited it. (I already edited all the other dev-ocean pages currently rendered on the docs site. This is the last one for now.)

I _didn't_ edit for technical accuracy.

When I wasn't sure if some markup was meaningful, I left it alone.

2018-11-23 14:12 UTC, kremalicious approved these changes

2018-11-26 22:41 UTC, dgossen requested changes
Made a few slight modifications, otherwise it looks good.

2018-11-27 08:35 UTC, ttmc commented
@Don I looked at your edits and they all look fine. Merging of this PR is blocked because your review "requested changes" but I don't think you intended that, since I don't see any requested changes. You can clear that block by clicking the link to "Approve changes" (even though there are none, other than the removal of a stray comma that I noticed in passing).

2018-11-27 08:35 UTC, ttmc commented
@dgossen  I looked at your edits and they all look fine. Merging of this PR is blocked because your review "requested changes" but I don't think you intended that, since I don't see any requested changes. You can clear that block by clicking the link to "Approve changes" (even though there are none, other than the removal of a stray comma that I noticed in passing).

2018-11-29 11:10 UTC, dgossen approved these changes

2018-11-29 11:12 UTC, merged